# This is a Docker Compose file for setting up the morphic-stack environment.

name: morphic-stack
services:
  morphic:
    build:
      context: . # The build context is the current directory
      dockerfile: Dockerfile
    command: bun dev # Use `bun dev -H 0.0.0.0` to listen on all interfaces
    env_file: .env.local
    ports:
      - '3000:3000'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: swissarmyknife
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
